<a href="https://colab.research.google.com/github/ScriptSmith70/Python/blob/main/Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [9]:
lst = [1,2,3,4]
arr=np.array(lst)

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.shape

(4,)

In [6]:
lst1=[1,2,3,4,5]
lst2=[6,7,8,9,10]
lst3=[7,8,9,10,11]

arr1 = np.array([lst1,lst2,lst3])

In [6]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 7,  8,  9, 10, 11]])

In [7]:
arr1.shape

(3, 5)

# **INDEXING**

Single colon[  :  ] - [Start : Stop : Step]  Stop is not included, it is exclusive

Double colon[ :: ] - [Step] Skips the elements

In [11]:
print(arr[2])

3


In [12]:
arr[2] = 8
arr

array([1, 2, 8, 4])

In [16]:
arr[1:]

array([2, 8, 4])

In [17]:
arr[1:3]

array([2, 8])

In [20]:
print(arr[-1]) ## Takes the last element

4


In [27]:
print(arr[:-1])  ## Removes the last elements

arr[:-2]         ## Removes the last 2 elements

[1 2 8]


array([1, 2])

In [25]:
print(arr[::])  # Prints the whole array

print(arr[:: -1]) # Reverse the array

[1 2 8 4]
[4 8 2 1]


In [32]:
arr[:: -2] ## Reverses and skips one element

array([4, 2])

In [34]:
arr[:: -3]  ## Reverses and skips 2 elements

array([4, 1])

In [35]:
arr.reshape(2,2)  ## Reshape the array

array([[1, 2],
       [8, 4]])

In [39]:
arr[arr<3]

array([1, 2])

In [38]:
arr * arr

array([ 1,  4, 64, 16])

In [41]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [44]:
np.random.randint(10,50,4)

array([39, 12, 48, 21])

Arange

In [3]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])